// Generated by diesel_ext

use crate::schema::*;
use crate::utils::{datetime_format, naive_date_format};
use diesel::prelude::*;
use serde::{Deserialize, Serialize};

use chrono::{NaiveDate, Utc, DateTime};


#[derive(Queryable, Selectable, Insertable, Debug, Clone, Identifiable, Deserialize, Serialize)]
pub struct Author {
    pub id: i32,
    pub name: String,
    pub urls: Option<Vec<Option<String>>>,
}

#[derive(Queryable, Selectable, Insertable, Debug, Clone, Identifiable, Deserialize, Serialize)]
pub struct ImageCollection {
    pub id: i32,
    pub description: Option<String>,
    #[serde(with = "naive_date_format")]
    pub date: NaiveDate,
}

#[derive(Queryable, Selectable, Insertable, Debug, Clone, Identifiable, Associations, Deserialize, Serialize)]
#[diesel(belongs_to(ImageCollection))]
#[diesel(belongs_to(ImageItem))]
#[diesel(primary_key(image_collection_id, image_item_id))]
pub struct ImageCollectionsImageItem {
    pub image_collection_id: i32,
    pub image_item_id: i32,
}

#[derive(Queryable, Selectable, Insertable, Debug, Clone, Identifiable, Associations, Deserialize, Serialize)]
#[diesel(belongs_to(Author))]
pub struct ImageItem {
    pub id: i32,
    #[serde(with = "naive_date_format")]
    pub date: NaiveDate,
    pub author_id: Option<i32>,
}

#[derive(Queryable, Selectable, Insertable, Debug, Clone, Identifiable, Associations, Serialize, Deserialize)]
#[diesel(belongs_to(ImageItem))]
pub struct LocalFile {
    pub id: i32,
    pub file_name: Option<String>,
    pub path: String,
    #[serde(with = "datetime_format")]
    pub created_at: DateTime<Utc>,
    pub image_item_id: i32,
}

#[derive(Queryable, Selectable, Insertable, Debug, Clone, Identifiable, Associations, Deserialize, Serialize)]
#[diesel(belongs_to(ImageItem))]
pub struct SocialPost {
    pub id: i32,
    #[serde(rename = "type")]
    pub type_: i32,
    pub url: String,
    pub image_item_id: i32,
}

#[derive(Queryable, Selectable, Insertable, Debug, Clone, Identifiable, Deserialize, Serialize)]
#[diesel(primary_key(token))]
pub struct ApiToken {
    pub token: String,
    pub admin: bool,
    #[serde(with = "datetime_format")]
    pub created_at: DateTime<Utc>,
}
